apiVersion: v1
kind: Service
metadata:
  name: python
spec:
  ports:
    - port: 3000
  selector:
    app: python
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: python
spec:
  selector:
    matchLabels:
      app: python
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - image: bilgicalpay/python-app
          name: python
          env:
            # Use secret in real usage
            - name: MYSQL_USERNAME
              value: "root"
            - name: MYSQL_PASSWORD
              value: "pass123"
            - name: MYSQL_INSTANCE_NAME
              value:
            - name: MYSQL_PORT_3306_TCP_ADDR
              value: "localhost"
            - name: MYSQL_PORT_3306_TCP_PORT
              value: "3306"
          ports:
            - containerPort: 3000
              name: python
      imagePullSecrets:
        - name: my-secret

