Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 6144
    v.cpus = 2
  end

  config.vm.box = "geerlingguy/ubuntu1604"

  
  # aşağıdaki admin panele gerek yok. ben denemek için koydum. istenirse kaldırılır
  config.vm.network "forwarded_port", guest: 8001, host: 8001 #kubernetes admin panel
  config.vm.network "forwarded_port", guest: 3000, host: 3000 #python application

  # Developer workspace'ini burada tutacak. eğer jar,war vs çıkmış olsa idi onu da tomcat apps altına maplerdik veya CD araçlarından birine geleneksel deploy yaptırırdık.
  
  config.vm.synced_folder ".", "/workspace/projects/vkdp/"
  
  # mysql verilerini makinede /mnt/data altına aldık. gluser vs denemedim ama o sistemler veyanfs vs ile daha güvenli hale getirilebilir.
  config.vm.synced_folder "./mysql/data", "/mnt/data"

  config.vm.provision :shell, :path => "./setup/docker.sh"
  config.vm.provision :shell, :path => "./setup/k8s.sh"
  config.vm.provision :shell, :path => "./mysql/run.sh"
end
