Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 6144
    v.cpus = 2
  end

  config.vm.box = "geerlingguy/ubuntu1604"

  config.vm.network "forwarded_port", guest: 8001, host: 8001 #kubernetes admin panel
  config.vm.network "forwarded_port", guest: 3000, host: 3000 #python application

  config.vm.synced_folder ".", "/workspace/projects/vkdp/"
  # config.vm.synced_folder "./mysql/data", "/mnt/data"

  config.vm.provision :shell, :path => "./setup/docker.sh"
  config.vm.provision :shell, :path => "./setup/k8s.sh"
  config.vm.provision :shell, :path => "./mysql/run.sh"
end
